version: '3'
services:

  php:
    build:
      context: ./docker/php
    image: selby/php:7.4-fpm-alpine
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: projects
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
